export default {
  companyName: 'Company Name',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  phone: 'Phone',
  phone2: 'Phone 2',
  address: 'Address',
  address2: 'Address 2',
  city: 'City',
  state: 'State',
  zipcode: 'Zip code',
  name: 'Name',
  year: 'Year',
  make: 'Make',
  model: 'Model',
  operable: 'Operable',
  color: 'Color',
  plate: 'Plate',
  vin: 'VIN',
  lot: 'Lot',
  carrierType: 'Carrier Type',
  availableDate: 'Available Date',
  deliveryDate: 'Delivery Date',
  basePrice: 'Base Price',
  sizeFee: 'Size Fee',
  inopFee: 'Inop Fee',
  enclosedFee: 'Enclosed Fee',
  deposit: 'Deposit',
  totalPrice: 'Total Price'
};
