name: '[DEVELOPMENT] Deploy'

# ALWAYS USE SINGLE QUOTES HERE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy AutoBook Pro
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      STAGE: dev
      S3_ASSETS_BUCKET_NAME: app.autobookpro.com
      OUTPUT_DIR: ./build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Install Serverless
        run: npm install -g serverless@latest
      - name: Install Dependencies
        run: make install-deps
      - name: Build
        run: make build-app
        env:
          NODE_ENV: production
      - name: Deploy
        run: make deploy-build
